### ISSUE TITLE
Contains incompatible tools version (5.5.0)

### ISSUE THREAD

**Issue by jyviko** [skytoup/shortuuid#1]
Getting the following error when compiling in Xcode 12.5.1 (12E507) that has swift-tools-version:5.3:
`'shortuuid' >= 1.0.0 cannot be used because no versions of 'shortuuid' match the requirement 1.0.1..<2.0.0 and 'shortuuid' 1.0.0 contains incompatible tools version (5.5.0)`

Can you update the minimum swift-tools-version to 5.3 ?

Thanks

**Comment by skytoup** [comment]
Hi, I did update the swift-tools-version to 5.1
